#!/bin/bash

set -euo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/app/vendor/bin

files=(
  settings.php
  updates_log.module
)

cd /app

set -x

echo "${files[*]}" \
| xargs --verbose --max-args=1 php -l

phpcs --runtime-set testVersion 8.1
phpstan analyze
psalm
