#!/bin/bash

set -euo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/app/vendor/bin

files=(
  settings.php
  updates_log.module
)

cd /app

set -x

for file in ${files[*]}
do
  php -l "$file"
  phpcs -sp --report=full --runtime-set testVersion 7.4 "$file"
done

phpstan analyze --level=5 --autoload-file scan-autoload.php -- ${files[*]}

psalm --show-info=true --php-version=7.4
