#!/bin/bash

set -xeuo pipefail
export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin

drupal_root=drupal

export PATH="$PATH:/app/$drupal_root/vendor/bin"

# cannot do this during the build
# because db is not available at the build time.
cd "/app/$drupal_root"

set +e
drush status bootstrap | grep -q Successful
status="$?"
set -e
if [[ "$status" -ne 0 ]]; then
  ./vendor/bin/drush site-install minimal -y
  ./vendor/bin/drush pm-install updates_log -y
fi
